---
- name: Install Packages
  apt: >
    pkg={{ ['postgresql','postgresql-contrib','python3-psycopg2', 'libpq-dev', 'acl'] }}
    state=present
    update-cache=yes
  tags: 
    - setup

- name: Create Database User
  when: postgresql is defined
  become: yes
  become_user: postgres
  postgresql_user: >
    user={{ postgresql.user }}
    password={{ postgresql.password }}
    port={{ postgresql.port }}
    role_attr_flags=CREATEDB,NOSUPERUSER
  tags: 
    - deploy

- name: Create Database
  when: postgresql is defined
  become: yes
  become_user: postgres
  postgresql_db: >
    name={{ postgresql.name }}
    owner={{ postgresql.user }}
    login_host={{ postgresql.host }}
    login_user={{ postgresql.user }}
    login_password={{ postgresql.password }}
    port={{ postgresql.port }}
  tags:
    - deploy

# Clean up commands that are never run unless DELETE tag is used
- name: DELETE Database
  when: postgresql is defined
  become: yes
  become_user: postgres
  postgresql_db: >
    name={{ postgresql.name }}
    owner={{ postgresql.user }}
    login_host={{ postgresql.host }}
    login_user={{ postgresql.user }}
    login_password={{ postgresql.password }}
    port={{ postgresql.port }}
    state=absent
  ignore_errors: yes
  tags:
    - DELETE
    - never


- name: DELETE Database User
  when: postgresql is defined
  become: yes
  become_user: postgres
  postgresql_user: >
    user={{ postgresql.user }}
    password={{ postgresql.password }}
    port={{ postgresql.port }}
    role_attr_flags=CREATEDB,NOSUPERUSER
    state=absent
  ignore_errors: yes
  tags: 
    - DELETE
    - never