---
- name: Configure all application processes
  hosts:
    - appservers
    - taskservers
  vars_files:
    - ../{{ inventory_name }}/group_vars/{{ env }}.yml
  become: yes
  roles:
    - role: uvicorn
    - role: celery

